### ISSUE TITLE
list commands does not give addresses

### ISSUE THREAD

**Issue by infernotower** [particl/testnet#9]
commands like listaddressgroupings, listaccounts, listreceivedbyaccounts does not shot addresses
![image](https://user-images.githubusercontent.com/26768749/26892239-30c3ea34-4bea-11e7-8b4b-ba0205984cd9.png)

**Comment by dasource** [comment]
Hi,

They are displaying no info because there is nothing to display.

```
dasource@part-test:~/testnet$ ./particl-cli listaccounts
{
  "": 50003.14906396,
  "nan": 0.00000000,
  "yay": 0.00000000
}
```
Its important to notice that if the account has 0 balance then you need the additional parameters `0 true`

```
dasource@part-test:~/testnet$ ./particl-cli listreceivedbyaddress 0 true
[
  {
    "address": "ppp8SVeg23gk9KziK5XKnHvQwkzCwU6w9w",
    "account": "yay",
    "amount": 0.00000000,
    "confirmations": 0,
    "label": "yay",
    "txids": [
    ]
  }, 
  {
    "address": "TetW7kJPDJz1imguRv8t9fWvjYYkwzJ1Mk2V7fuekg9smE2CVzb9kgroAjStotABgCghsfqMMXBn8qtWNqLp7du5dRWZ9UAKxX8Nkw",
    "account": "nan",
    "amount": 0.00000000,
    "confirmations": 0,
    "label": "nan",
    "txids": [
    ]
  }
]
```

You will not see any genesis import account details or addresses, this is by design.
Once you begin to use your funds it will automatically move into your real account and thus show the relevant details.

Hope that explains how it works.
